[package]
name = "tfc-anvil-solver"
version = "0.1.0"
edition = "2024"
description = "CLI tool for solving TFC Anvil recipes"
repository = "https://github.com/AshleyThx/TFC-Anvil-Solver"
publish = false

[dependencies]
colored = "3.0.0"
